#!/usr/bin/with-contenv bash

export HOME=/tmp

exec \
    s6-notifyoncheck -d -n 300 -w 5000 -c "nc -z localhost 3003" \
        cd /app/immich/machine-learning s6-setuidgid abc \
            /config/cuda-venv/bin/serve run app.main:ingress --host 0.0.0.0 --port 3003
